#!/usr/bin/env python3
"""Generate registry.yaml FROM DISK.

The catalogue drifted because it was maintained by hand: the README said "47
independent scrapers" and "42 Python packages" while sources/ held 90
directories, and .github/dependabot.yml still said "38 scraper packages".
Numbers that are typed cannot be trusted; numbers that are generated can.

Usage:
    python scripts/build_registry.py            # write registry.yaml
    python scripts/build_registry.py --check    # fail if it is stale (CI)
"""
import argparse
import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ROOT / "sources"
REGISTRY = ROOT / "registry.yaml"

_UA_RE = re.compile(r'User-Agent["\']?\s*[:=]\s*["\']([^"\']+)["\']')
_DELAY_RE = re.compile(r"^DELAY\s*=\s*([0-9.]+)", re.M)
# Surfaced because it silently disagrees across the tree: the same corpus is
# admitted at 80 characters by bea/aaib/bfu/tsb/cenipa/nsib/cins/ahac/ansv, at
# 200 by ntsbcarol, and at 300 by ovv/india/aaibmy/sacaa/rosap and others.
# Which is right is a data decision, not a refactor — but it should at least
# be visible in one place rather than buried in fourteen files.
_FLOOR_RE = re.compile(r"^_?(?:NARRATIVE_FLOOR|MIN_NARRATIVE)\s*=\s*(\d+)", re.M)


def _docstring(path):
    try:
        return (ast.get_docstring(ast.parse(path.read_text(encoding="utf-8",
                                                           errors="replace"))) or "").strip()
    except SyntaxError:
        return ""


def _first(pattern, texts, group=1):
    for t in texts:
        m = pattern.search(t)
        if m:
            return m.group(group)
    return None


def describe(pkg_dir):
    code = pkg_dir.name
    ingest = pkg_dir / f"{code}_ingest"
    top_scripts = sorted(pkg_dir.glob("*.py"))
    py_files = sorted(ingest.glob("*.py")) if ingest.is_dir() else top_scripts
    texts = [p.read_text(encoding="utf-8", errors="replace") for p in py_files]

    if ingest.is_dir():
        shape = "package"
        verbs = []
        cli = ingest / "cli.py"
        if cli.is_file():
            m = re.search(r"choices=\[([^\]]+)\]", cli.read_text(encoding="utf-8"))
            if m:
                verbs = [v.strip().strip("\"'") for v in m.group(1).split(",")]
        doc_src = ingest / "pipeline.py"
        if not doc_src.is_file():
            doc_src = cli if cli.is_file() else (py_files[0] if py_files else None)
    else:
        shape = "script"
        verbs = ["argv"]
        doc_src = py_files[0] if py_files else None

    # "behaviour" means a test that imports the source and asserts something
    # about what it does. Keying on the absence of ast.parse was wrong once the
    # smoke tests started using ast to check the __main__ guard: what separates
    # a real test from a parse is whether it loads the module at all.
    tests_dir = pkg_dir / "tests"
    module_names = {f"{code}_ingest", f"{code}_scraper", code}
    tier = "none"
    if tests_dir.is_dir():
        tier = "smoke"
        for t in sorted(tests_dir.glob("test_*.py")):
            body = t.read_text(encoding="utf-8", errors="replace")
            imports_source = any(
                re.search(rf"^\s*(?:from\s+{re.escape(m)}\b|import\s+{re.escape(m)}\b)",
                          body, re.M)
                for m in module_names
            )
            if not imports_source:
                continue
            if t.name == "test_smoke.py":
                continue          # imports it, but only asserts it loads
            tier = "behaviour"
            break
    has_real_tests = tier == "behaviour"

    summary = ""
    if doc_src is not None and doc_src.is_file():
        lines = _docstring(doc_src).splitlines()
        summary = lines[0] if lines else ""

    return {
        "code": code,
        "shape": shape,
        "verbs": verbs,
        "user_agent": _first(_UA_RE, texts),
        "delay_seconds": _first(_DELAY_RE, texts),
        "narrative_floor": _first(_FLOOR_RE, texts),
        "tests": tier,
        "summary": summary,
    }


def render():
    rows = [describe(d) for d in sorted(SOURCES.iterdir()) if d.is_dir()]
    out = [
        "# GENERATED by scripts/build_registry.py - do not edit by hand.",
        "# Run `python scripts/build_registry.py` after adding or changing a source.",
        f"# python_sources: {len(rows)}",
        f"# four_verb_packages: {sum(1 for r in rows if r['shape'] == 'package')}",
        f"# single_file_scripts: {sum(1 for r in rows if r['shape'] == 'script')}",
        f"# with_behaviour_tests: {sum(1 for r in rows if r['tests'] == 'behaviour')}",
        f"# import_smoke_only: {sum(1 for r in rows if r['tests'] == 'smoke')}",
        f"# no_tests: {sum(1 for r in rows if r['tests'] == 'none')}",
        "sources:",
    ]
    for r in rows:
        out.append(f"  - code: {r['code']}")
        out.append(f"    shape: {r['shape']}")
        out.append(f"    verbs: [{', '.join(r['verbs'])}]")
        out.append(f"    tests: {r['tests']}")
        if r["delay_seconds"]:
            out.append(f"    delay_seconds: {r['delay_seconds']}")
        if r["narrative_floor"]:
            out.append(f"    narrative_floor: {r['narrative_floor']}")
        if r["user_agent"]:
            out.append(f"    user_agent: {r['user_agent']!r}")
        if r["summary"]:
            out.append(f"    summary: {r['summary']!r}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if registry.yaml is stale")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = REGISTRY.read_text(encoding="utf-8") if REGISTRY.exists() else ""
        if current != text:
            print("registry.yaml is stale - run: python scripts/build_registry.py",
                  file=sys.stderr)
            return 1
        print("registry.yaml in sync")
        return 0
    REGISTRY.write_text(text, encoding="utf-8")
    print(f"wrote {REGISTRY.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
