package foreignsearch

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

// carolEndpoint is the NTSB CAROL public query API.
const carolEndpoint = "https://data.ntsb.gov/carol-main-public/api/Query/Main"

// carolSessionEndpoint creates a CAROL session.
const carolSessionEndpoint = "https://data.ntsb.gov/carol-main-public/api/Session/CreateSession"

// carolCaseURLTemplate is the public accident-investigation page for a given NtsbNo.
// Source: https://data.ntsb.gov/carol-main-public/api/Lookup/ClientSettings/List → ExternalURLs.AccidentReportLink
const carolCaseURLTemplate = "https://www.ntsb.gov/investigations/Pages/%s.aspx"

// carolReportURLTemplate is the PDF report generated by Mkey.
// Source: ExternalURLs.SaftiReportLink
const carolReportURLTemplate = "https://data.ntsb.gov/carol-repgen/api/Aviation/ReportMain/GenerateNewestReport/%s/pdf"

// carolSupportedCountries is the set of in-scope US-delegated ISO 3166-1 alpha-2 codes
// accepted by the CAROL Event.Country lookup.
// Verified 2026-06-23: CAROL expects the ISO2 code directly (e.g. "BS"), NOT the full
// country name (e.g. "Bahamas" returns ResultListCount=0; "BS" returns 413).
var carolSupportedCountries = map[string]struct{}{
	"BS": {},
	"MH": {},
	"FM": {},
	"PW": {},
	"BB": {},
	"AG": {},
}

// carolFieldMap maps CAROL field names as returned by the Query/Main endpoint
// (each row has Fields[].FieldName / Fields[].Values).
// Captured from live fixture testdata/ntsb_carol.json (Bahamas, BS).
//
// Row structure:
//
//	{ "Fields": [{"FieldName":"NtsbNo","Values":["GAA23WA068"]}, ...], "EntryId": "..." }
//
// Top-level response:
//
//	{ "Results": [...], "Columns": [...], "ResultListCount": 413, "MaxResultCountReached": true }

// carolResponse is the top-level CAROL Query/Main JSON response.
type carolResponse struct {
	Results         []carolResult `json:"Results"`
	ResultListCount int           `json:"ResultListCount"`
}

// carolResult is one row returned by CAROL.
type carolResult struct {
	Fields []carolField `json:"Fields"`
}

// carolField is a single field in a CAROL result row.
type carolField struct {
	FieldName string   `json:"FieldName"`
	Values    []string `json:"Values"`
}

// carolQueryPayload is the POST body for Query/Main.
type carolQueryPayload struct {
	QueryGroups   []carolQueryGroup `json:"QueryGroups"`
	TargetCollection string         `json:"TargetCollection"`
	AndOr         string            `json:"AndOr"`
	SortColumn    interface{}       `json:"SortColumn"`
	SortDescending bool             `json:"SortDescending"`
	SessionID     int               `json:"SessionId"`
	ResultSetSize int               `json:"ResultSetSize"`
	ResultSetOffset int             `json:"ResultSetOffset"`
}

type carolQueryGroup struct {
	QueryRules []carolQueryRule `json:"QueryRules"`
	AndOr      string           `json:"AndOr"`
}

type carolQueryRule struct {
	FieldName string   `json:"FieldName"`
	RuleType  int      `json:"RuleType"`
	Values    []string `json:"Values"`
	Columns   []string `json:"Columns"`
	Operator  string   `json:"Operator"`
}

// parseNTSB converts a raw CAROL Query/Main JSON response into ForeignRecord slice.
// It is a pure function: network calls belong in ntsbClient.Search.
//
// Mapping:
//   - ForeignRef  = NtsbNo (stable NTSB case number)
//   - Title       = "VehicleMake VehicleModel, City, Country" (no Synopsis field in API)
//   - OccurrenceDate = EventDate trimmed to yyyy-mm-dd prefix
//   - OriginalURL  = https://www.ntsb.gov/investigations/Pages/${NtsbNo}.aspx
//   - ReportURL    = https://…/GenerateNewestReport/${Mkey}/pdf  (only when RepGenFlag=="1")
//
// Rows missing NtsbNo are skipped and counted in warnings.
// A non-JSON body returns a non-nil error.
func parseNTSB(raw []byte) (recs []ForeignRecord, warnings int, err error) {
	var resp carolResponse
	if err := json.Unmarshal(raw, &resp); err != nil {
		return nil, 0, fmt.Errorf("foreignsearch: parseNTSB: unmarshal: %w", err)
	}

	for _, row := range resp.Results {
		fields := carolExtractFields(row.Fields)

		ntsbNo := fields["NtsbNo"]
		if ntsbNo == "" {
			warnings++
			continue
		}

		// OccurrenceDate: EventDate is "2023-01-06T11:15:00Z" — take date prefix.
		occDate := ""
		if ed := fields["EventDate"]; ed != "" {
			if i := strings.IndexByte(ed, 'T'); i > 0 {
				occDate = ed[:i]
			} else {
				occDate = ed
			}
		}

		// Title: build from make/model + city because CAROL search results carry no synopsis.
		title := buildCarolTitle(fields)

		// OriginalURL: canonical NTSB investigation page.
		origURL := fmt.Sprintf(carolCaseURLTemplate, ntsbNo)

		// ReportURL: PDF report exists only when RepGenFlag=="1" and Mkey is present.
		reportURL := ""
		if fields["RepGenFlag"] == "1" {
			if mkey := fields["Mkey"]; mkey != "" {
				reportURL = fmt.Sprintf(carolReportURLTemplate, mkey)
			}
		}

		recs = append(recs, ForeignRecord{
			ForeignRef:     ntsbNo,
			Title:          title,
			OccurrenceDate: occDate,
			OriginalURL:    origURL,
			ReportURL:      reportURL,
		})
	}
	return recs, warnings, nil
}

// parseNTSBPage is parseNTSB plus the response's ResultListCount — the
// server's count of ALL matching rows, independent of how many this one page
// returned (GO-CP-6). ntsbClient.Search uses it to detect when a single
// ResultSetSize=500 page was truncating a larger result set (BS was known to
// be 413/500 already, i.e. right at the edge) and to know when to stop
// paginating.
func parseNTSBPage(raw []byte) (recs []ForeignRecord, warnings int, resultListCount int, err error) {
	var resp carolResponse
	if err := json.Unmarshal(raw, &resp); err != nil {
		return nil, 0, 0, fmt.Errorf("foreignsearch: parseNTSBPage: unmarshal: %w", err)
	}
	recs, warnings, err = parseNTSB(raw)
	return recs, warnings, resp.ResultListCount, err
}

// carolExtractFields collapses a []carolField into a string→string map using
// the first value of each field (empty string when Values is empty).
func carolExtractFields(fields []carolField) map[string]string {
	m := make(map[string]string, len(fields))
	for _, f := range fields {
		if len(f.Values) > 0 {
			m[f.FieldName] = f.Values[0]
		} else {
			m[f.FieldName] = ""
		}
	}
	return m
}

// buildCarolTitle constructs a human-readable title from CAROL fields.
// No plain-text synopsis is present in the Query/Main response.
func buildCarolTitle(f map[string]string) string {
	make_ := strings.TrimSpace(f["VehicleMake"])
	model := strings.TrimSpace(f["VehicleModel"])
	city := strings.TrimSpace(f["City"])
	country := strings.TrimSpace(f["Country"])

	aircraft := strings.TrimSpace(make_ + " " + model)
	if aircraft == "" {
		aircraft = "Unknown aircraft"
	}

	var parts []string
	parts = append(parts, aircraft)
	if city != "" {
		parts = append(parts, city)
	}
	if country != "" {
		parts = append(parts, country)
	}
	return strings.Join(parts, ", ")
}

// carolPageSize is CAROL's ResultSetSize per page. carolMaxPages caps
// pagination (GO-CP-6) — 40 pages * 500 rows = 20,000 rows is far beyond any
// realistic single-country result set; the cap exists so a server bug
// (e.g. never returning a short page) can't loop forever.
const (
	carolPageSize = 500
	carolMaxPages = 40
)

// ntsbClient implements AuthorityClient against the live NTSB CAROL API.
type ntsbClient struct {
	http *http.Client

	// queryEndpoint / sessionEndpoint default to carolEndpoint /
	// carolSessionEndpoint; overridable in tests to point at an httptest server.
	queryEndpoint   string
	sessionEndpoint string

	// pageDelay is slept between pages (not before the first) to keep request
	// pacing polite against a public government API. Overridable (0) in tests.
	pageDelay time.Duration
}

// NewNTSBClient returns an AuthorityClient backed by the live CAROL API.
func NewNTSBClient(timeout time.Duration) AuthorityClient {
	return &ntsbClient{
		http:            &http.Client{Timeout: timeout},
		queryEndpoint:   carolEndpoint,
		sessionEndpoint: carolSessionEndpoint,
		pageDelay:       500 * time.Millisecond,
	}
}

// Search queries the CAROL API for aviation accidents in the given country,
// paginating ResultSetOffset by carolPageSize until a short page is returned
// (fewer than carolPageSize rows) or carolMaxPages is reached (GO-CP-6: BS
// alone was already at 413/500 — one hardcoded page silently dropped any
// country with more than 500 matching cases). countryISO2 must be one of the
// keys in carolSupportedCountries.
func (c *ntsbClient) Search(ctx context.Context, countryISO2 string) ([]ForeignRecord, error) {
	iso2 := strings.ToUpper(countryISO2)
	if _, ok := carolSupportedCountries[iso2]; !ok {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: unsupported country ISO2 %q", countryISO2)
	}

	// Create a CAROL session (required — queries without SessionId return HTTP 500).
	sessionID, err := c.createSession(ctx)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: create session: %w", err)
	}

	seen := make(map[string]bool)
	var all []ForeignRecord
	lastResultListCount := 0
	pagesFetched := 0
	for page := 0; page < carolMaxPages; page++ {
		if page > 0 && c.pageDelay > 0 {
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case <-time.After(c.pageDelay):
			}
		}

		offset := page * carolPageSize
		body, err := c.fetchPage(ctx, iso2, sessionID, offset)
		if err != nil {
			return nil, err
		}
		recs, _, resultListCount, err := parseNTSBPage(body)
		if err != nil {
			return nil, err
		}
		lastResultListCount = resultListCount
		pagesFetched++

		for _, r := range recs {
			if seen[r.ForeignRef] {
				continue
			}
			seen[r.ForeignRef] = true
			all = append(all, r)
		}

		if len(recs) < carolPageSize {
			break // short page: this was the last one
		}
	}

	// A full page on the very last iteration means carolMaxPages was hit
	// without ever seeing a short page — the result set may still be
	// truncated. Also warn whenever the server's own count disagrees with
	// what we collected (belt-and-braces against a dedup collapse hiding a
	// gap). Recorded as a warning (GO-CP-6) rather than failing the job: a
	// partial result set is still useful.
	if lastResultListCount > len(all) {
		fmt.Fprintf(os.Stderr, "CAROL_TRUNCATED country=%s collected=%d total=%d pages=%d\n",
			iso2, len(all), lastResultListCount, pagesFetched)
	}

	return all, nil
}

// fetchPage builds and executes one CAROL Query/Main page request at the
// given ResultSetOffset. CAROL Event.Country accepts ISO2 codes directly
// (e.g. "BS"), not full names.
func (c *ntsbClient) fetchPage(ctx context.Context, iso2 string, sessionID, offset int) ([]byte, error) {
	payload := carolQueryPayload{
		QueryGroups: []carolQueryGroup{
			{
				QueryRules: []carolQueryRule{
					{
						FieldName: "Country",
						RuleType:  0,
						Values:    []string{iso2},
						Columns:   []string{"Event.Country"},
						Operator:  "is",
					},
				},
				AndOr: "And",
			},
		},
		TargetCollection: "cases",
		AndOr:            "And",
		SortColumn:       nil,
		SortDescending:   false,
		SessionID:        sessionID,
		ResultSetSize:    carolPageSize,
		ResultSetOffset:  offset,
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: marshal query: %w", err)
	}

	endpoint := c.queryEndpoint
	if endpoint == "" {
		endpoint = carolEndpoint
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(payloadBytes))
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: unexpected status %d", resp.StatusCode)
	}

	var buf bytes.Buffer
	if _, err := buf.ReadFrom(resp.Body); err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: read body: %w", err)
	}
	return buf.Bytes(), nil
}

// createSession obtains a CAROL session ID by POSTing to the session endpoint.
func (c *ntsbClient) createSession(ctx context.Context) (int, error) {
	endpoint := c.sessionEndpoint
	if endpoint == "" {
		endpoint = carolSessionEndpoint
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, nil)
	if err != nil {
		return 0, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return 0, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("unexpected status %d", resp.StatusCode)
	}

	var sessionID int
	if err := json.NewDecoder(resp.Body).Decode(&sessionID); err != nil {
		return 0, fmt.Errorf("decode session id: %w", err)
	}
	return sessionID, nil
}
