package foreignsearch

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// carolEndpoint is the NTSB CAROL public query API.
const carolEndpoint = "https://data.ntsb.gov/carol-main-public/api/Query/Main"

// carolSessionEndpoint creates a CAROL session.
const carolSessionEndpoint = "https://data.ntsb.gov/carol-main-public/api/Session/CreateSession"

// carolCaseURLTemplate is the public accident-investigation page for a given NtsbNo.
// Source: https://data.ntsb.gov/carol-main-public/api/Lookup/ClientSettings/List → ExternalURLs.AccidentReportLink
const carolCaseURLTemplate = "https://www.ntsb.gov/investigations/Pages/%s.aspx"

// carolReportURLTemplate is the PDF report generated by Mkey.
// Source: ExternalURLs.SaftiReportLink
const carolReportURLTemplate = "https://data.ntsb.gov/carol-repgen/api/Aviation/ReportMain/GenerateNewestReport/%s/pdf"

// carolSupportedCountries is the set of in-scope US-delegated ISO 3166-1 alpha-2 codes
// accepted by the CAROL Event.Country lookup.
// Verified 2026-06-23: CAROL expects the ISO2 code directly (e.g. "BS"), NOT the full
// country name (e.g. "Bahamas" returns ResultListCount=0; "BS" returns 413).
var carolSupportedCountries = map[string]struct{}{
	"BS": {},
	"MH": {},
	"FM": {},
	"PW": {},
	"BB": {},
	"AG": {},
}

// carolFieldMap maps CAROL field names as returned by the Query/Main endpoint
// (each row has Fields[].FieldName / Fields[].Values).
// Captured from live fixture testdata/ntsb_carol.json (Bahamas, BS).
//
// Row structure:
//
//	{ "Fields": [{"FieldName":"NtsbNo","Values":["GAA23WA068"]}, ...], "EntryId": "..." }
//
// Top-level response:
//
//	{ "Results": [...], "Columns": [...], "ResultListCount": 413, "MaxResultCountReached": true }

// carolResponse is the top-level CAROL Query/Main JSON response.
type carolResponse struct {
	Results         []carolResult `json:"Results"`
	ResultListCount int           `json:"ResultListCount"`
}

// carolResult is one row returned by CAROL.
type carolResult struct {
	Fields []carolField `json:"Fields"`
}

// carolField is a single field in a CAROL result row.
type carolField struct {
	FieldName string   `json:"FieldName"`
	Values    []string `json:"Values"`
}

// carolQueryPayload is the POST body for Query/Main.
type carolQueryPayload struct {
	QueryGroups   []carolQueryGroup `json:"QueryGroups"`
	TargetCollection string         `json:"TargetCollection"`
	AndOr         string            `json:"AndOr"`
	SortColumn    interface{}       `json:"SortColumn"`
	SortDescending bool             `json:"SortDescending"`
	SessionID     int               `json:"SessionId"`
	ResultSetSize int               `json:"ResultSetSize"`
	ResultSetOffset int             `json:"ResultSetOffset"`
}

type carolQueryGroup struct {
	QueryRules []carolQueryRule `json:"QueryRules"`
	AndOr      string           `json:"AndOr"`
}

type carolQueryRule struct {
	FieldName string   `json:"FieldName"`
	RuleType  int      `json:"RuleType"`
	Values    []string `json:"Values"`
	Columns   []string `json:"Columns"`
	Operator  string   `json:"Operator"`
}

// parseNTSB converts a raw CAROL Query/Main JSON response into ForeignRecord slice.
// It is a pure function: network calls belong in ntsbClient.Search.
//
// Mapping:
//   - ForeignRef  = NtsbNo (stable NTSB case number)
//   - Title       = "VehicleMake VehicleModel, City, Country" (no Synopsis field in API)
//   - OccurrenceDate = EventDate trimmed to yyyy-mm-dd prefix
//   - OriginalURL  = https://www.ntsb.gov/investigations/Pages/${NtsbNo}.aspx
//   - ReportURL    = https://…/GenerateNewestReport/${Mkey}/pdf  (only when RepGenFlag=="1")
//
// Rows missing NtsbNo are skipped and counted in warnings.
// A non-JSON body returns a non-nil error.
func parseNTSB(raw []byte) (recs []ForeignRecord, warnings int, err error) {
	var resp carolResponse
	if err := json.Unmarshal(raw, &resp); err != nil {
		return nil, 0, fmt.Errorf("foreignsearch: parseNTSB: unmarshal: %w", err)
	}

	for _, row := range resp.Results {
		fields := carolExtractFields(row.Fields)

		ntsbNo := fields["NtsbNo"]
		if ntsbNo == "" {
			warnings++
			continue
		}

		// OccurrenceDate: EventDate is "2023-01-06T11:15:00Z" — take date prefix.
		occDate := ""
		if ed := fields["EventDate"]; ed != "" {
			if i := strings.IndexByte(ed, 'T'); i > 0 {
				occDate = ed[:i]
			} else {
				occDate = ed
			}
		}

		// Title: build from make/model + city because CAROL search results carry no synopsis.
		title := buildCarolTitle(fields)

		// OriginalURL: canonical NTSB investigation page.
		origURL := fmt.Sprintf(carolCaseURLTemplate, ntsbNo)

		// ReportURL: PDF report exists only when RepGenFlag=="1" and Mkey is present.
		reportURL := ""
		if fields["RepGenFlag"] == "1" {
			if mkey := fields["Mkey"]; mkey != "" {
				reportURL = fmt.Sprintf(carolReportURLTemplate, mkey)
			}
		}

		recs = append(recs, ForeignRecord{
			ForeignRef:     ntsbNo,
			Title:          title,
			OccurrenceDate: occDate,
			OriginalURL:    origURL,
			ReportURL:      reportURL,
		})
	}
	return recs, warnings, nil
}

// carolExtractFields collapses a []carolField into a string→string map using
// the first value of each field (empty string when Values is empty).
func carolExtractFields(fields []carolField) map[string]string {
	m := make(map[string]string, len(fields))
	for _, f := range fields {
		if len(f.Values) > 0 {
			m[f.FieldName] = f.Values[0]
		} else {
			m[f.FieldName] = ""
		}
	}
	return m
}

// buildCarolTitle constructs a human-readable title from CAROL fields.
// No plain-text synopsis is present in the Query/Main response.
func buildCarolTitle(f map[string]string) string {
	make_ := strings.TrimSpace(f["VehicleMake"])
	model := strings.TrimSpace(f["VehicleModel"])
	city := strings.TrimSpace(f["City"])
	country := strings.TrimSpace(f["Country"])

	aircraft := strings.TrimSpace(make_ + " " + model)
	if aircraft == "" {
		aircraft = "Unknown aircraft"
	}

	var parts []string
	parts = append(parts, aircraft)
	if city != "" {
		parts = append(parts, city)
	}
	if country != "" {
		parts = append(parts, country)
	}
	return strings.Join(parts, ", ")
}

// ntsbClient implements AuthorityClient against the live NTSB CAROL API.
type ntsbClient struct {
	http *http.Client
}

// NewNTSBClient returns an AuthorityClient backed by the live CAROL API.
func NewNTSBClient(timeout time.Duration) AuthorityClient {
	return &ntsbClient{http: &http.Client{Timeout: timeout}}
}

// Search queries the CAROL API for aviation accidents in the given country.
// countryISO2 must be one of the keys in carolCountryNames.
func (c *ntsbClient) Search(ctx context.Context, countryISO2 string) ([]ForeignRecord, error) {
	body, err := c.fetch(ctx, countryISO2)
	if err != nil {
		return nil, err
	}
	recs, _, err := parseNTSB(body)
	return recs, err
}

// fetch builds and executes the CAROL query for the given ISO2 country code.
// It first obtains a session ID (required by the API), then runs the query.
// CAROL Event.Country accepts ISO2 codes directly (e.g. "BS"), not full names.
func (c *ntsbClient) fetch(ctx context.Context, countryISO2 string) ([]byte, error) {
	iso2 := strings.ToUpper(countryISO2)
	if _, ok := carolSupportedCountries[iso2]; !ok {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: unsupported country ISO2 %q", countryISO2)
	}

	// Create a CAROL session (required — queries without SessionId return HTTP 500).
	sessionID, err := c.createSession(ctx)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: create session: %w", err)
	}

	payload := carolQueryPayload{
		QueryGroups: []carolQueryGroup{
			{
				QueryRules: []carolQueryRule{
					{
						FieldName: "Country",
						RuleType:  0,
						Values:    []string{iso2},
						Columns:   []string{"Event.Country"},
						Operator:  "is",
					},
				},
				AndOr: "And",
			},
		},
		TargetCollection: "cases",
		AndOr:            "And",
		SortColumn:       nil,
		SortDescending:   false,
		SessionID:        sessionID,
		ResultSetSize:    500,
		ResultSetOffset:  0,
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: marshal query: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, carolEndpoint, bytes.NewReader(payloadBytes))
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: unexpected status %d", resp.StatusCode)
	}

	var buf bytes.Buffer
	if _, err := buf.ReadFrom(resp.Body); err != nil {
		return nil, fmt.Errorf("foreignsearch: ntsbClient: read body: %w", err)
	}
	return buf.Bytes(), nil
}

// createSession obtains a CAROL session ID by POSTing to the session endpoint.
func (c *ntsbClient) createSession(ctx context.Context) (int, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, carolSessionEndpoint, nil)
	if err != nil {
		return 0, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return 0, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("unexpected status %d", resp.StatusCode)
	}

	var sessionID int
	if err := json.NewDecoder(resp.Body).Decode(&sessionID); err != nil {
		return 0, fmt.Errorf("decode session id: %w", err)
	}
	return sessionID, nil
}
